# Simple workflow for deploying static content to GitHub Pages
name: Deploy content to Pages
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
concurrency: ci-${{ github.ref }} 
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            lfs: true # Fetches LFS data
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Build
        run: |
            npm install
            npm run build
            npm run build-storybook -- --output-dir dist/storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            folder: dist
            target-folder: ${{ steps.extract_branch.outputs.branch }}